### ISSUE TITLE
Is this library still under maintenance?

### ISSUE THREAD

**Issue by sailxjx** [makinacorpus/easydict#30]
The latest version on pip is 1.9, which was released three years ago. Even there are still some new commits in this repo, why not release the newest version to pip?

**Comment by leplatrem** [comment]
I don't want to sound like I'm the official maintainer here, but since 1.9, only the package metadata was adjusted https://github.com/makinacorpus/easydict/compare/1.9...master 

I guess this library just does what it's supposed to do. And none of the current opened pull-requests are mergeable.

**Comment by sailxjx** [comment]
Thanks @leplatrem, that's a reasonable answer.
