### ISSUE TITLE
Fail to update the value!

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [makinacorpus/easydict#6]
I think this is an **important** problem when I debug a large project code. Finally I found it is caused by the weird characteristics `easydict` has. For example: 

First, let's define a easydict instance.

```
>>> from easydict import EasyDict as edict
>>> C = edict()
>>> C.t = 1
>>> C
{'t': 1}
>>> C.t
1
>>> C['t']
1
```

Everything works well till now. Then let's update the value through the easydict style:

```
>>> C.t = 2
>>> C
{'t': 2}
>>> C.t
2
>>> C['t']
2
```

It seems everything goes well too. However, if we update the value with original dictionary style:

```
>>> C['t'] = 3
>>> C
{'t': 3}
>>> C.t
2
>>> C['t']
3
```

Find something strange? We could not access the value we want through easydict style. Actually, it seems that there exist two keyword of 't'. I do not know what happened. Could the author fix this problem? I think this will be really dangerous when using in big project.

Thanks a lot!

**Comment by leplatrem** [comment]
Thanks for reporting!
Have a look at the code, it's pretty short, don't hesitate to open a PR with a fix...

**Comment by leplatrem** [comment]
Even if it breaks the API by the way ;)

**Comment by kinredon** [comment]
@Xiaoming-Zhao Do you solve this issue? I meet the same problem where I get different results between PyTorch DDP and single GPU training. This is very dangerous.

**Comment by Xiaoming-Zhao** [comment]
Hi @kinredon , I later use the following one. It lacks some features from this repo but it met my needs. Hope this helps.

https://github.com/NVlabs/stylegan2/blob/bf0fe0baba9fc7039eae0cac575c1778be1ce3e3/dnnlib/util.py#L35-L48

**Comment by kinredon** [comment]
@Xiaoming-Zhao Thanks for your reply!
